services:
  - type: web
    name: hkd-webapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hkd.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your_postgres_db_name
          property: connectionString
      - key: DJANGO_SU_NAME
        value: admin
      - key: DJANGO_SU_EMAIL
        value: admin@example.com
      - key: DJANGO_SU_PASSWORD
        value: yourStrongPassword123
