services:
  - type: web
    name: hkd-webapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "poetry run gunicorn hkd.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hkddb
          property: connectionString
      - key: DJANGO_SU_NAME
        value: hkdadmin
      - key: DJANGO_SU_EMAIL
        value: sonawanedivyani148@gmail.com
      - key: DJANGO_SU_PASSWORD
        value: Hare@Krishna
