# Generated by Django 5.2 on 2025-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("Bhagavad Gita Course", "Bhagavad Gita Course"),
                            ("Diksha Preparation Course", "Diksha Preparation Course"),
                            ("Digital Marketing Course", "Digital Marketing Course"),
                        ],
                        default="Bhagavad Gita Course",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("event_description", models.TextField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
    ]
