# Generated by Django 5.1.7 on 2025-03-27 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="event_description",
            field=models.TextField(default="No description available."),
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="Untitled Event", max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
