# Generated by Django 5.1.7 on 2025-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_event_description_remove_event_name_event_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(),
        ),
    ]
